/**
 * 
 */
package com.taskslistproject.taskslist.dto;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author Esteban Triviño
 * This class is created because of the implementation of the DTO Design Pattern
 * which allows have a class for data transfer.
 * 
 * This class is the template to map the Status class from
 * "com.tasklistproject.takslist.domain"
 * 
 * Mapping is generated by the MapStruct library
 */
public class StatusDTO {
	
	
	/**
	 * Constructor without params
	 */
	public StatusDTO() {
		super();
	}

	/**
	 * Constructor with params
	 * @param statusId
	 * @param description
	 */
	public StatusDTO(Integer statusId, @NotNull @Size(min = 1, max = 100) String description) {
		super();
		this.statusId = statusId;
		this.description = description;
	}
	
	private Integer statusId;
	
	@NotNull
	@Size(min = 1, max = 100)
	private String description;
	
	//Auto generated sets and gets
	
	/**
	 * @return the statusId
	 */
	public Integer getStatusId() {
		return statusId;
	}

	/**
	 * @param statusId the statusId to set
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}
	
}
