/**
 * 
 */
package com.taskslistproject.taskslist.dto;

import javax.validation.constraints.NotNull;

/**
 * @author Esteban Triviño
 * This class is created because of the implementation of the DTO Design Pattern
 * which allows have a class for data transfer.
 * 
 * This class is the template to map the Task class from
 * "com.tasklistproject.takslist.domain"
 * 
 * Mapping is generated by the MapStruct library
 */
public class TaskDTO {
	
	/**
	 * Default constructor
	 */
	public TaskDTO() {
	}
	
	/**
	 * Constructor with parameters
	 * @param taskId
	 * @param description
	 * @param tasklist
	 * @param done
	 * @param user
	 * @param status
	 */
	public TaskDTO(Integer taskId, @NotNull String description, @NotNull Integer tasklist, String done, Integer user,
			@NotNull Integer status) {
		super();
		this.taskId = taskId;
		this.description = description;
		this.tasklist = tasklist;
		this.done = done;
		this.user = user;
		this.status = status;
	}

	private Integer taskId;
	
	@NotNull
	private String description;
	
	@NotNull
	private Integer tasklist;
	
	private String done;
	
	private Integer user;
	
	@NotNull
	private Integer status;
	
	//Auto generated getters and setters
	
	/**
	 * @return the taskId
	 */
	public Integer getTaskId() {
		return taskId;
	}

	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the tasklist
	 */
	public Integer getTasklist() {
		return tasklist;
	}

	/**
	 * @param tasklist the tasklist to set
	 */
	public void setTasklist(Integer tasklist) {
		this.tasklist = tasklist;
	}

	/**
	 * @return the done
	 */
	public String getDone() {
		return done;
	}

	/**
	 * @param done the done to set
	 */
	public void setDone(String done) {
		this.done = done;
	}

	/**
	 * @return the user
	 */
	public Integer getUser() {
		return user;
	}

	/**
	 * @param user the user to set
	 */
	public void setUser(Integer user) {
		this.user = user;
	}

	/**
	 * @return the status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
	
}
