/**
 * 
 */
package com.taskslistproject.taskslist.dto;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author Esteban Triviño
 * This class is created because of the implementation of the DTO Design Pattern
 * which allows have a class for data transfer.
 * 
 * This class is the template to map the Tasklist class from
 * "com.tasklistproject.takslist.domain"
 * 
 * Mapping is generated by the MapStruct library
 */
public class TasklistDTO {

	/**
	 * Constructor without parameters
	 */
	public TasklistDTO() {
		super();
	}
	
	/**
	 * Constructor with parameters
	 * @param tasklistId
	 * @param name
	 */
	public TasklistDTO(Integer tasklistId, @NotNull @Size(min = 1, max = 100) String name) {
		super();
		this.tasklistId = tasklistId;
		this.name = name;
	}

	private Integer tasklistId;
	
	@NotNull
	@Size(min = 1, max = 100)
	private String name;
	
	//Auto generated set's and get's
	/**
	 * @return the tasklistId
	 */
	public Integer getTasklistId() {
		return tasklistId;
	}

	/**
	 * @param tasklistId the tasklistId to set
	 */
	public void setTasklistId(Integer tasklistId) {
		this.tasklistId = tasklistId;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	

}
