package com.taskslistproject.taskslist.dto;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author Esteban Triviño
 * This class is created because of the implementation of the DTO Design Pattern
 * which allows have a class for data transfer.
 * 
 * This class is the template to map the User class from
 * "com.tasklistproject.takslist.domain" to a DTO object
 * 
 * Mapping is generated by the MapStruct library
 */
public class UserDTO {
	
	/**
	 * Constructor without parameters
	 */
	public UserDTO() {
		super();
	}
	
	/**
	 * Constructor with parameters
	 * @param userId
	 * @param name
	 * @param email
	 * @param password
	 */
	public UserDTO(Integer userId, @NotNull @Size(min = 1, max = 100) String name,
			@NotNull @Size(min = 1, max = 100) String email, @Size(min = 1, max = 100) String password) {
		super();
		this.userId = userId;
		this.name = name;
		this.email = email;
		this.password = password;
	}

	private Integer userId;
	
	@NotNull
	@Size(min = 1, max = 100)
	private String name;
	
	@NotNull
	@Size(min = 1, max = 100)
	private String email;

	@Size(min = 1, max = 100)
	private String password;
	
	
	//Auto-generated getters and setters
	
	/**
	 * @return the userId
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	
}
